version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: my_sql
    platform: linux/amd64
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass